server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /user {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }

    location /shop {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }

    location /shop-type {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }

    location /blog {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }

    location /follow {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }

    location /voucher {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }

    location /voucher-order {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }

    location /upload {
        proxy_pass http://app:8081;
        proxy_set_header Host $host;
    }
}