export const endpointCatalog = [
  { key: "POST /user/code", module: "用户", label: "发送验证码" },
  { key: "POST /user/login", module: "用户", label: "验证码登录" },
  { key: "POST /user/logout", module: "用户", label: "登出（后端未完成）" },
  { key: "GET /user/me", module: "用户", label: "当前用户" },
  { key: "GET /user/info/{id}", module: "用户", label: "用户详情" },
  { key: "GET /user/{id}", module: "用户", label: "用户基础信息" },
  { key: "POST /user/sign", module: "用户", label: "签到" },
  { key: "GET /user/sign/count", module: "用户", label: "连续签到天数" },
  { key: "GET /shop/{id}", module: "商铺", label: "商铺详情" },
  { key: "POST /shop", module: "商铺", label: "新增商铺" },
  { key: "PUT /shop", module: "商铺", label: "更新商铺" },
  { key: "GET /shop/of/type", module: "商铺", label: "按分类查商铺" },
  { key: "GET /shop/of/name", module: "商铺", label: "按名称查商铺" },
  { key: "GET /shop-type/list", module: "分类", label: "商铺分类列表" },
  { key: "POST /blog", module: "博客", label: "发布博客" },
  { key: "PUT /blog/like/{id}", module: "博客", label: "点赞 / 取消点赞" },
  { key: "GET /blog/of/me", module: "博客", label: "我的博客" },
  { key: "GET /blog/hot", module: "博客", label: "热门博客" },
  { key: "GET /blog/{id}", module: "博客", label: "博客详情" },
  { key: "GET /blog/likes/{id}", module: "博客", label: "点赞用户列表" },
  { key: "GET /blog/of/user", module: "博客", label: "用户博客列表" },
  { key: "GET /blog/of/follow", module: "博客", label: "关注推送流" },
  { key: "PUT /follow/{id}/{isFollow}", module: "关注", label: "关注 / 取关" },
  { key: "GET /follow/or/not/{id}", module: "关注", label: "是否关注" },
  { key: "GET /follow/common/{id}", module: "关注", label: "共同关注" },
  { key: "POST /voucher", module: "优惠券", label: "新增普通券" },
  { key: "POST /voucher/seckill", module: "优惠券", label: "新增秒杀券" },
  { key: "GET /voucher/list/{shopId}", module: "优惠券", label: "店铺券列表" },
  { key: "POST /voucher-order/seckill/{id}", module: "秒杀", label: "秒杀下单" },
  { key: "POST /upload/blog", module: "上传", label: "上传博客图片" },
  { key: "GET /upload/blog/delete", module: "上传", label: "删除博客图片" },
];
