export const moduleMeta = [
  {
    id: "hero",
    label: "总览",
    path: "/",
    routePath: "",
    title: "系统总览",
    description: "环境配置、登录状态和模块入口。",
    showInSidebar: true,
  },
  {
    id: "user",
    label: "用户",
    path: "/user",
    routePath: "user",
    title: "用户模块",
    description: "验证码登录、会话状态、签到和用户信息查询。",
    showInSidebar: true,
  },
  {
    id: "shop-types",
    label: "分类",
    path: "/shop-types",
    routePath: "shop-types",
    title: "商铺分类",
    description: "商铺分类列表和图片资源预览。",
    showInSidebar: true,
  },
  {
    id: "shops",
    label: "商铺",
    path: "/shops",
    routePath: "shops",
    title: "商铺模块",
    description: "商铺查询、创建、更新和详情上下文。",
    showInSidebar: true,
  },
  {
    id: "blogs",
    label: "博客",
    path: "/blogs",
    routePath: "blogs",
    title: "博客模块",
    description: "博客发布、热榜、点赞和关注流。",
    showInSidebar: true,
  },
  {
    id: "follow",
    label: "关注",
    path: "/follow",
    routePath: "follow",
    title: "关注模块",
    description: "关注、关注状态和共同关注查询。",
    showInSidebar: true,
  },
  {
    id: "vouchers",
    label: "优惠券",
    path: "/vouchers",
    routePath: "vouchers",
    title: "优惠券与秒杀",
    description: "普通券、秒杀券和秒杀下单。",
    showInSidebar: true,
  },
  {
    id: "upload",
    label: "上传",
    path: "/upload",
    routePath: "upload",
    title: "图片上传",
    description: "博客图片上传、预览和删除。",
    showInSidebar: true,
  },
  {
    id: "logs",
    label: "诊断",
    path: "/logs",
    routePath: "logs",
    title: "接口诊断",
    description: "接口覆盖矩阵、最近响应和请求日志。",
    showInSidebar: true,
  },
];

export const sidebarModules = moduleMeta.filter((item) => item.showInSidebar);
